cuda_visible_devices: [ 1 ]
algorithm: SAC
algorithm_config: null
env_name: HalfCheetah-v5
env_config:
  exclude_current_positions_from_observation: false
timesteps: 2000000
eval_num_episodes: 256
eval_frequency: 5000
log_wandb: true
